Update puavo-remotemounts-helper and puavo-update-gtk-bookmarks from puavo-os as is.

diff --git a/client/puavo-update-gtk-bookmarks b/client/puavo-update-gtk-bookmarks
--- a/client/puavo-update-gtk-bookmarks
+++ b/client/puavo-update-gtk-bookmarks
@@ -9,15 +9,11 @@ fi
 mode=${1:-}
 
 puavo_domain=$(cat /etc/puavo/domain)
-puavo_hosttype=$(cat /etc/puavo/hosttype)
 
 user_primary_group=$(id -gn)
 
-has_device_tag() {
-  jq -r .tags[] /etc/puavo/device.json | grep -qx "$1"
-}
-
-use_sambahomes() { has_device_tag sambahomes; }
+is_remotemounts_enabled=$(puavo-conf puavo.mounts.by_user_from_bootserver.enabled)
+is_nethomes_enabled=$(puavo-conf puavo.mounts.nethomes.enabled)
 
 filter_out_our_bookmarks() {
   local bookmarksfile
@@ -54,23 +50,18 @@ update_bookmarks() {
 
   filter_out_our_bookmarks "${bookmarksfile}" > "${tmpfile}"
 
-  case "$puavo_hosttype" in
-    fatclient|ltspserver)
-      if use_sambahomes; then
-	echo "file://${HOME}/.puavo-sharedir.schooldir/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
-      else
-	echo "file:///home/share/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
-      fi
-      ;;
-    laptop)
+  if [ "${is_nethomes_enabled}" = 'true' ]; then
+    echo "file:///home/share/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
+  fi
+
+  if [ "${is_remotemounts_enabled}" = 'true' ]; then
       remote_host=$(dig SRV "_sambaserver._tcp.${puavo_domain}" +short \
           | sed -r -n 's/^[0-9]+ [0-9]+ 139 (.*)\./\1/p' | head -n1)
       if [ -n "${remote_host}" ]; then
           echo "smb://${remote_host}/${USER} ${userdir_displayname}"
           echo "smb://${remote_host}/share/${sharename}/${user_primary_group} ${schooldir_displayname}"
       fi >>"${tmpfile}"
-      ;;
-  esac
+  fi
 
   mv "${tmpfile}" "${bookmarksfile}"
 }
@@ -100,39 +91,23 @@ for bookmark_file in ~/.config/gtk-3.0/bookmarks ~/.gtk-bookmarks; do
                    "$bookmark_file"
 done
 
-
-# handle links from user home directory to gvfs-mounts for applications
-# that do not understand gvfs
+# Handle links from user home directory to gvfs-mounts for applications
+# that do not understand gvfs (and do not know about gtk-bookmarks).
+# "puavo-remotemounts-helper" handles these for those that have
+# "puavo.mounts.by_user_from_bootserver.enabled" == true
+# (but --with-cleanups is useful also in that case).
 
 if [ "$mode" = '--with-cleanups' ]; then
+  rmdir ~/.puavo-sharedir.schooldir 2>/dev/null || true
+
   # remove stale links (maybe created later)
   for linkname in 'Yhteiset'     'Delade filer' 'Share' \
                   'Verkkokansio' 'Nätverksmapp' 'Network folder'; do
     [ -h ~/"$linkname" ] && rm -f ~/"$linkname"
   done
-
-  case "$puavo_hosttype" in
-    fatclient|ltspserver)
-      if ! use_sambahomes; then
-        # old stuff, remove
-        rmdir ~/.puavo-sharedir.schooldir 2>/dev/null || true
-      fi
-      ;;
-    laptop)
-      # old stuff, remove
-      rmdir ~/.puavo-sharedir.schooldir \
-            ~/.puavo-sharedir.userdir 2>/dev/null || true
-      ;;
-  esac
 fi
 
-case "$puavo_hosttype" in
-  fatclient|ltspserver)
-    if use_sambahomes; then
-      ln -fns ~/.puavo-sharedir.schooldir ~/"${schooldir_displayname}"
-    else
-      ln -fns "/home/share/${sharename}/${user_primary_group}" \
-              ~/"${schooldir_displayname}"
-    fi
-    ;;
-esac
+if [ "${is_nethomes_enabled}" = 'true' ]; then
+  ln -fns "/home/share/${sharename}/${user_primary_group}" \
+          ~/"${schooldir_displayname}"
+fi
